service: flavorli

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  dynamodb: # Setup dynamodb to run locally
    stages:
      - dev
      - prod
      - staging
    start:
      port: 8000
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:custom.tableNames.recipes}
            sources: [src/seed-data/Recipes.json]
          - table: ${self:custom.tableNames.users}
            sources: [src/seed-data/Users.json]

  prefix: ${self:service}-${self:provider.region}-${self:provider.stage}
  tableNames:
    recipes: ${self:custom.prefix}-Recipes
    users: ${self:custom.prefix}-Users

functions:
  graphql:
    handler: dist/index.graphqlHandler
    role: FlavorliLambdaRole
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: FlavorliApiGatewayAuthorizer
      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: FlavorliApiGatewayAuthorizer
    environment:
      DYNAMODB_PORT: ${self:custom.dynamodb.start.port}
      STAGE: ${self:provider.stage}
      RECIPE_TABLE: ${self:custom.tableNames.recipes}
      USERS_TABLE: ${self:custom.tableNames.users}

resources:
  Resources:
    FlavorliBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.prefix}-bucket
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    FlavorliBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: 'FlavorliBucket'
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action:
                - 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: 'FlavorliBucket'
                    - '/*'

    FlavorliCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.prefix}-userPool
        AliasAttributes:
          - phone_number
          - email
        AutoVerifiedAttributes:
          - phone_number
        Schema:
          - Name: email
            Required: true
          - Name: gender
            Required: true
          - Name: phone_number
            Required: true
        SmsConfiguration:
          ExternalId: 'generate-your-own-uuid-here'
          SnsCallerArn: !GetAtt FlavorliLambdaRole.Arn

    FlavorliCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.prefix}-userPoolClient
        GenerateSecret: false
        UserPoolId:
          Ref: 'FlavorliCognitoUserPool'

    RecipeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNames.recipes}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNames.users}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    FlavorliLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-lambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - cognito-idp.amazonaws.com
              Action: sts:AssumeRole
              Condition:
                StringEquals:
                  sts:ExternalId:
                    - 'generate-your-own-uuid-here'
        Policies:
          - PolicyName: 'Dynamo-ServiceRole-Policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'dynamodb:Query'
                    - 'dynamodb:BatchWriteItem'
                    - 'dynamodb:GetItem'
                    - 'dynamodb:BatchGetItem'
                    - 'dynamodb:DeleteItem'
                    - 'dynamodb:PutItem'
                    - 'dynamodb:Scan'
                    - 'dynamodb:UpdateItem'
                  Resource:
                    - !GetAtt RecipeTable.Arn
                    - !GetAtt UserTable.Arn
          - PolicyName: 'Sns-ServiceRole-Policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'sns:*'
                  Resource:
                    - '*'

    FlavorliApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: ${self:custom.prefix}-authorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [FlavorliCognitoUserPool, Arn]
        IdentitySource: method.request.header.Authorization

  Outputs:
    FlavorliBucketURL:
      Description: 'FlavorliBucket Website URL'
      Value:
        'Fn::GetAtt': [FlavorliBucket, WebsiteURL]
    FlavorliCognitoUserPoolId:
      Description: 'Flavorli Cognito User Pool ID'
      Value:
        Ref: 'FlavorliCognitoUserPool'
    FlavorliCognitoUserPoolClientId:
      Description: 'Flavorli Cognito User Pool Client ID'
      Value:
        Ref: 'FlavorliCognitoUserPoolClient'
